Repository FiveEat42/yebalja.com, pull requests merged in 2020-06, with the labels that each got.

#5 add description of Yebalja.com in README.md
  README.md
Labels: documentation

#6 Update README.md
  README.md
Labels: documentation

#17 Add home/daelee
  .gitignore
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/pure.html
  public/robots.txt
  src/App.js
  src/App.test.js
  src/components/CustomizedTimeline.js
  src/components/Footer.js
  src/components/HorizontalTimeline.js
  src/components/Jumbotron.js
  src/components/SectionBox.js
  src/components/Table.js
  src/components/TimelineCard.js
  src/fonts/NEXON Lv2 Gothic Bold.ttf
  src/index.js
  src/logo.svg
  src/scripts/ScriptHorizontalTimeline.js
  src/serviceWorker.js
  src/setupTests.js
  src/styles/App.css
  src/styles/Footer.css
  src/styles/HorizontalTimeline.css
  src/styles/Jumbotron.css
  src/styles/SectionBox.css
  src/styles/Table.css
  src/styles/index.css
Labels: front-end

#22 Integrating node with React server for data transfer
  .gitignore
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/pure.html
  client/public/robots.txt
  client/src/App.js
  client/src/App.test.js
  client/src/components/CustomizedTimeline.js
  client/src/components/Footer.js
  client/src/components/HorizontalTimeline.js
  client/src/components/Jumbotron.js
  client/src/components/SectionBox.js
  client/src/components/Table.js
  client/src/components/TimelineCard.js
  client/src/fonts/NEXON Lv2 Gothic Bold.ttf
  client/src/index.js
  client/src/logo.svg
  client/src/scripts/ScriptHorizontalTimeline.js
  client/src/serviceWorker.js
  client/src/setupTests.js
  client/src/styles/App.css
  client/src/styles/Footer.css
  client/src/styles/HorizontalTimeline.css
  client/src/styles/Jumbotron.css
  client/src/styles/SectionBox.css
  client/src/styles/Table.css
  client/src/styles/index.css
  client/test
  package-lock.json
  package.json
  server.js
Labels: back-end
